steps: 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/tz-feo-staging/feo-pypsa/pypsa-earth-image', '-f','./infra/Dockerfile', '.']
images:
  - 'europe-west2-docker.pkg.dev/tz-feo-staging/feo-pypsa/pypsa-earth-image'